name: Build and Push Docker Images

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'
      - 'docker-ci'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          # based on branch push tag latest for main and dev for dev
          tags: erasme/maquette_augmentee_backend:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
